format_version: v1.0
type: UniqueComponent
attributes: {id: sysNetPic32mzw1}
children:
- type: Symbols
  children:
  - type: Combo
    attributes: {id: SYS_NET_MODE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: SERVER}
  - type: Integer
    attributes: {id: SYS_NET_PORT}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '5555'}
- type: ElementPosition
  attributes: {x: '124', y: '195', id: sysNetPic32mzw1}
