format_version: v1.0
type: UniqueComponent
attributes: {id: sysWifiPic32mzw1}
children:
- type: Symbols
  children:
  - type: Combo
    attributes: {id: SYS_WIFI_MODE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: AP}
- type: ElementPosition
  attributes: {x: '29', y: '63', id: sysWifiPic32mzw1}
